version: "3.9"
services:
  web:
    build: .
    ports:
      - "5000"  #make this 9090:5000
  
  loadbalancer:
    image: 'dockercloud/haproxy:latest'
    links:
      - pyapp
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 80:80