version: "3.9"
services:
  backend1:
    build: ./backend1
    expose:
      - "5000"  #make this 9090:5000
    networks:
      public_net:
        ipv4_address: ${backend_1_IP}

  backend2:
    build: ./backend2
    expose:
      - "5000"  #make this 9090:5000
    networks:
      public_net:
        ipv4_address: ${backend_2_IP}

  haproxy_img:
          build: ./haproxy
          ports:
              - 9090:80
          #expose:
          #    - 80
          networks:
              public_net:
                  ipv4_address: ${HA_PROXY_IP}
          environment:
              - backend_1_IP=${backend_1_IP}
              - backend_2_IP=${backend_2_IP}
              - backend_EXPOSED_PORT=${backend_EXPOSED_PORT}
networks:
    public_net:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: ${NETWORK_SUBNET}